lazypdf: add command line parser.

diff --git a/lazypdf b/lazypdf
--- a/lazypdf
+++ b/lazypdf
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Usage: ./lazypdf [PROJECT_DIR]
+# Usage: ./lazypdf [options] [argument ...]
+# run this script inside project directory.
 # project directory should contain c source files eg. <source>.c
 # also corresponding png file <source>.png for it to insert program output image
 
@@ -7,37 +8,46 @@ set -e
 set -o pipefail
 
 usage() {
-    echo 'Usage: ./lazypdf [PROJECT_DIR] -o [PDF]
+    echo 'Usage: ./lazypdf [options] [argument ..]
+    run this script inside project directory.
     project directory should contain c source files eg. <source>.c
-    also corresponding png file <source>.png for it to insert program output image'
+    also corresponding png file <source>.png for it to insert program output image
+
+    options:
+        -o    specify output pdf file' 
 }
 
+PROJECT_DIR="${PWD}"
+FILE_PDF="${PROJECT_DIR}/lazyPdf.pdf"
+FILE_MARKDOWN="${PROJECT_DIR}/lazyMarkdown.md"
 
-if [[ $# -eq 0 ]]; then
-    PROJECT_DIR="$PWD"
-fi
+while getopts ":ho" opt; do
+  case ${opt} in
+    h ) usage
+        exit 0
+      ;;
+    o ) shift
+        FILE_PDF="$1"
+      ;;
+    \? ) echo "Invalid Option: -$OPTARG" 1>&2
+         usage
+         exit 1
+      ;;
+  esac
+done
+shift $((OPTIND -1))
 
-if [[ ! -z "$1" ]]; then
-    PROJECT_DIR="$1"
-else
+program_files=$(find "${PROJECT_DIR}" -maxdepth 1 -iregex '.*\.\(c\|cpp\)' | sort)
+if [[ -z "${program_files}" ]]; then
+    echo "error: no source files found in ${PWD}"
     usage
     exit 1
 fi
 
-
-program_files=$(find "${PROJECT_DIR}" -maxdepth 1 -iregex '.*\.\(c\|cpp\)' | sort)
-if [[ -z "${program_files}" ]]; then
-    echo "(error) no source files found"
-    exit 1
-fi
-
-FILE_PDF="${PROJECT_DIR}/program.pdf"
-FILE_MARKDOWN="./outfile.md"
 if [[ -f $FILE_MARKDOWN ]]; then
     rm $FILE_MARKDOWN
     touch $FILE_MARKDOWN
 fi
-
 
 get_png_section_f_file() {
     _source_file="${1%.*}" 	
